cors:
  originPatterns: http://localhost:9000
security:
  jwt:
    token:
      secret-key: 5ccr37
      expire-lenth: 360000
spring:
  application:
    name: udemy-rest-springboot
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/udemy_rest_springboot?useTimezone=true&serverTimeZone=UTC
    username: SVC_UDEMY
    password: a.123456
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
    properties:
      show-sql: false
server:
  port: 9000

springdoc:
  paths-to-match:
    - /api/**/v1/**
    - /auth/**
  swagger-ui:
    use-root-path: true
