--
-- PostgreSQL database dump
--

-- Dumped from database version 16.3
-- Dumped by pg_dump version 16.3

-- Started on 2024-08-28 17:29:41

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 218 (class 1259 OID 16527)
-- Name: books; Type: TABLE; Schema: public; Owner: svc_person
--

CREATE TABLE public.books (
    id bigint NOT NULL,
    author character varying(255),
    launch_date timestamp(6) without time zone,
    price double precision NOT NULL,
    title character varying(255)
);


ALTER TABLE public.books OWNER TO svc_person;

--
-- TOC entry 217 (class 1259 OID 16526)
-- Name: books_id_seq; Type: SEQUENCE; Schema: public; Owner: svc_person
--

ALTER TABLE public.books ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.books_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 4839 (class 0 OID 16527)
-- Dependencies: 218
-- Data for Name: books; Type: TABLE DATA; Schema: public; Owner: svc_person
--



--
-- TOC entry 4845 (class 0 OID 0)
-- Dependencies: 217
-- Name: books_id_seq; Type: SEQUENCE SET; Schema: public; Owner: svc_person
--

SELECT pg_catalog.setval('public.books_id_seq', 1, false);


--
-- TOC entry 4694 (class 2606 OID 16533)
-- Name: books books_pkey; Type: CONSTRAINT; Schema: public; Owner: svc_person
--

ALTER TABLE ONLY public.books
    ADD CONSTRAINT books_pkey PRIMARY KEY (id);


-- Completed on 2024-08-28 17:29:41

--
-- PostgreSQL database dump complete
--

